# Generated by Django 3.2.4 on 2021-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv', '0002_apartments_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('area', models.CharField(choices=[('19,30', '19,30'), ('56,20', '56,20'), ('64,55', '64,55'), ('61,70', '61,70'), ('47,60', '47,60'), ('122,10', '122,10'), ('42,20', '42,20'), ('41,90', '41,90'), ('40,80', '40,80'), ('39,90 (1-L-sleva)', '39,90 (1-L-sleva)'), ('39,90 (2-R-sprava)', '39,90 (2-R-sprava)'), ('42,60', '42,60'), ('63 (1-L-sleva)', '63 (1-L-sleva)'), ('63 (2-R-sprava)', '63 (2-R-sprava)'), ('30,15', '30,15'), ('33,75', '33,75')], max_length=25)),
                ('available', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='zayavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apartments',
            name='available',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='floor',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '3'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=2),
        ),
    ]
